#! /usr/bin/env python3

import os
import sys
import locale
import subprocess
import platform
import tkinter as tk
import tkinter.filedialog

VERSION = '1.0'

# Internationalisation
def _(text):
    try:
        lang = locale.getdefaultlocale()[0][0:2]
        text = TEXT[lang][text]
    except:
        pass

    return text
 
TOOLTIP_TARGET_RATIO = 'Frequency of occurrence of the target image (between 0 and 100).'
TOOLTIP_TARGET_IMG = 'Image to use as target. If omitted, then a random image shall be chosen.'
TOOLTIP_IMG_DIR = 'Directory of images (supported formats: jpg, png).'
TOOLTIP_INSTRUCTION = 'Text to be printed on the first line of each page.'

# French tooltips
TOOLTIP_TARGET_RATIO_fr = "Fréquence d'apparition de l'image cible parmi les autres (entre 0 et 100)."
TOOLTIP_TARGET_IMG_fr = 'Image à utiliser comme cible. Si elle n\'est pas précisée, alors une image est tirée au hasard.'
TOOLTIP_IMG_DIR_fr = 'Répertoire où se trouvent les images à utiliser (formats supportés: jpg, png).'
TOOLTIP_INSTRUCTION_fr = 'Texte à afficher en tête de chaque page.'

TEXT = { 'fr':
        {'Page format':'Format de page',
         'Page orientation':'Orientation de la page',
         'landscape':'paysage',
         'Number of pages':'Nombre de pages',
         'Image layout':'Placement des images',
         'grid':'grille',
         'not aligned':'non aligné',
         'Images per page':'Images par page',
         'Image directory':'Répertoire d\'images',
         'Target ratio (%)':'Ratio de la cible (%)',
         'Target image':'Image cible',
         'Instruction':'Consigne',
         'Generate PDF':'Générer un PDF',
         'Generate PDF and open':'Générer un PDF et l\'ouvrir',
         'Exit':'Quitter',
         'cancelled':'annulé',
         'Choose a file name for the generated PDF':'Choisissez un nom de fichier pour le PDF',
         'ok':'ok',
         'error':'erreur',
         TOOLTIP_TARGET_RATIO:TOOLTIP_TARGET_RATIO_fr,
         TOOLTIP_TARGET_IMG:TOOLTIP_TARGET_IMG_fr,
         TOOLTIP_IMG_DIR:TOOLTIP_IMG_DIR_fr,
         TOOLTIP_INSTRUCTION:TOOLTIP_INSTRUCTION_fr,
         '':''}
       }


def open_file_with_default_application(filepath):
    system = platform.system()
    if system == 'Darwin': # macOS
        subprocess.call(['open', filepath])
    elif system == 'Windows':
        os.startfile(filepath)
    else: # Linux variants
        subprocess.call(['xdg-open', filepath])

WIDTH_LABEL = '20'

def create_choice(parent, label_text, selected, *values):
    """Create a Frame with a label and an OptionMenu
    """
    frame = tk.Frame(parent)
    label_text += ':'
    label = tk.Label(frame, text=label_text, width=WIDTH_LABEL, anchor=tk.E)
    label.pack(side='left')
    frame.value = tk.StringVar()
    frame.value.set(selected)
    frame.option_menu = tk.OptionMenu(frame, frame.value, *values)
    frame.option_menu.pack(side='left')
    frame.pack(side='top', anchor=tk.W)
    return frame


def validate_percent(text):
    """Prevent typing other characters than digits or numbers greater than 100
    
    Allow the user to erase all characters.
    """
    if text == '': return True
    try:
        v = int(text)
        if v < 0: return False
        if v > 100: return False
        return True
    except:
        return False


def validate_page_num(text):
    """Prevent typing other characters than digits
    
    Allow the user to erase all characters.
    """
    if text == '': return True
    try:
        v = int(text)
        if v < 0: return False
        return True
    except:
        return False


def entry_set_default_value_if_empty(event):
    """Rrestore default value, if empty"""
    if event.widget.get() == '':
        event.widget.delete(0, tk.END)
        event.widget.insert(0, event.widget.default_value)


def create_input(parent, label_text, validate_func=None, size=5, default=None):
    """Create a Frame with a label and an OptionMenu
    """
    frame = tk.Frame(parent)
    label_text += ':'
    label = tk.Label(frame, text=label_text, width=WIDTH_LABEL, anchor=tk.E)
    label.pack(side='left')
    frame.entry = tk.Entry(frame, width=size)
    frame.entry.pack(side='left')
    if validate_func:
        cmd = frame.entry.register(validate_func)
        frame.entry.config(validate='key')
        frame.entry.config(validatecommand=(cmd, '%P'))

    if default:
        frame.entry.insert(0, default)
        frame.entry.default_value = default
        frame.entry.bind("<FocusOut>", entry_set_default_value_if_empty)

    frame.pack(side='top', anchor=tk.W)
        
    return frame


class CreateTooltip(object):
    """Create a tooltip for a given widget
    """
    def __init__(self, widget, text):
        self.showup_delay = 500     # miliseconds
        self.wraplength = 180   # pixels
        self.widget = widget
        self.text = text
        self.widget.bind("<Enter>", self.enter)
        self.widget.bind("<Leave>", self.leave)
        self.widget.bind("<ButtonPress>", self.leave)
        self.timer_id = None
        self.toplevel_window = None

    def enter(self, event=None):
        self.schedule()

    def leave(self, event=None):
        self.unschedule()
        self.hide_tooltip()

    def schedule(self):
        self.unschedule()
        self.timer_id = self.widget.after(self.showup_delay, self.show_tooltip)

    def unschedule(self):
        timer_id = self.timer_id
        self.timer_id = None
        if timer_id:
            self.widget.after_cancel(timer_id)

    def show_tooltip(self, event=None):
        x = y = 0
        x, y, cx, cy = self.widget.bbox()
        x += self.widget.winfo_rootx() + 25
        y += self.widget.winfo_rooty() + 20
        # creates a toplevel window
        self.toplevel_window = tk.Toplevel(self.widget)
        # Leaves only the label and removes the app window
        self.toplevel_window.wm_overrideredirect(True)
        self.toplevel_window.wm_geometry("+%d+%d" % (x, y))
        label = tk.Label(self.toplevel_window, text=self.text, justify='left',
                         background="#ffffdf", relief='solid', borderwidth=1,
                         wraplength=self.wraplength)
        label.pack(ipadx=1)

    def hide_tooltip(self):
        toplevel_window = self.toplevel_window
        self.toplevel_window= None
        if toplevel_window:
            toplevel_window.destroy()


class Application(tk.Frame):
    def __init__(self, master=None):
        super().__init__(master)
        self.master = master
        self.pack(fill=tk.BOTH)
        self.create_widgets()


    def create_widgets(self):

        self.page_orientation = create_choice(self, _('Page orientation'), _('portrait'),
                                              _('portrait'), _('landscape'))
        self.page_orientation.pack(side="top")

        self.page_format = create_choice(self, _('Page format'), 'A4', 'A4', 'A3')

        self.num_pages = create_input(self, _('Number of pages'), validate_page_num, default='1')

        self.img_layout = create_choice(self, _('Image layout'), _('grid'),
                                       _('grid'), _('not aligned'))

        self.images_per_page = create_input(self, _('Images per page'), validate_page_num, default='36')

        self.target_ratio = create_input(self, _('Target ratio (%)'), validate_percent, default='20')
        CreateTooltip(self.target_ratio, _(TOOLTIP_TARGET_RATIO))

        self.target_img = create_input(self, _('Target image'), size=50)
        self.target_img.entry.bind('<Button-1>', self.cb_choose_target_img)
        CreateTooltip(self.target_img, _(TOOLTIP_TARGET_IMG))

        self.src_img_dir = create_input(self, _('Image directory'), size=50)
        self.src_img_dir.entry.bind('<Button-1>', self.cb_choose_img_src_dir)
        self.src_img_dir.entry.insert(0, 'letters')
        CreateTooltip(self.src_img_dir, _(TOOLTIP_IMG_DIR))

        self.instruction = create_input(self, _('Instruction'), size=50)
        CreateTooltip(self.instruction, _(TOOLTIP_INSTRUCTION))

        # add a separation
        tk.Frame(self, height=30).pack(side='top')

        # Buttons
        self.frame_buttons = tk.Frame(self)
        self.frame_buttons.pack(side='top', anchor=tk.E, padx=15)

        self.button_gen_pdf = tk.Button(self.frame_buttons, text=_('Generate PDF'),
                                        command=self.generate_pdf)
        self.button_gen_pdf.pack(side='left')

        self.button_gen_pdf = tk.Button(self.frame_buttons, text=_('Generate PDF and open'),
                                        command=self.generate_pdf_and_open)
        self.button_gen_pdf.pack(side='left')
        
        self.button_exit = tk.Button(self.frame_buttons, text=_('Exit'), command=self.exit)
        self.button_exit.pack(side='left')
        self.master.bind('<Control-q>', self.exit)

        # add a separation
        tk.Frame(self, height=15).pack(side='top')

        # Messages
        self.console = tk.Text(self)
        self.console.pack(side="top", fill=tk.BOTH, expand=1)



    def cb_choose_target_img(self, event):
        filepath = tk.filedialog.askopenfilename()
        if filepath:
            # set the path in the widget
            self.target_img.entry.delete(0, tk.END)
            self.target_img.entry.insert(0, filepath)


    def cb_choose_img_src_dir(self, event):
        directory = tk.filedialog.askdirectory()
        if directory:
            # set the path in the widget
            self.src_img_dir.entry.delete(0, tk.END)
            self.src_img_dir.entry.insert(0, directory)


    def exit(self, event=None):
        self.master.destroy()


    def collect_miximg_args(self):
        args = get_miximg_exe()
        args.append('--images-per-page')
        args.append(self.images_per_page.entry.get())
        args.append('--page-format')
        args.append(self.page_format.value.get())
        args.append('--page-orientation')
        page_orientation = self.page_orientation.value.get()
        if page_orientation == _('portrait'):
            args.append('portrait')
        else:
            args.append('landscape')
        if self.num_pages.entry.get():
            args.append('--pages')
            args.append(self.num_pages.entry.get())
        args.append('--layout')
        img_layout = self.img_layout.value.get()
        if img_layout == _('grid'):
            args.append('grid')
        else:
            args.append('random')
               
        if self.target_ratio.entry.get():
            args.append('--target-ratio')
            args.append(self.target_ratio.entry.get())
        if self.target_img.entry.get():
            args.append('--target')
            args.append(self.target_img.entry.get())
        if self.instruction.entry.get():
            args.append('--text')
            args.append(self.instruction.entry.get())
        args.append(self.src_img_dir.entry.get())

        return args


    def generate_pdf_and_open(self, event=None):
        (returncode, pdf_filepath) = self.generate_pdf(event)
        if returncode == 0:
            self.console.insert(tk.END, 'Opening PDF...')
            open_file_with_default_application(pdf_filepath)


    def generate_pdf(self, event=None):
        # ask for output file
        pdf_filepath = tk.filedialog.asksaveasfilename(filetypes=(('PDF', '*.pdf'),),
                                                 title=_('Choose a file name for the generated PDF'))
        if not pdf_filepath:
            self.console.insert(tk.END, _('cancelled')+'\n')
            return

        if pdf_filepath[-4:] != '.pdf':
            pdf_filepath += '.pdf'

        # run the 'miximg' program
        args = self.collect_miximg_args()
        args.append('--output')
        args.append(pdf_filepath)

        self.console.insert(tk.END, ' '.join(args) + '\n')
        self.console.update()

        p = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        # display the result in the console
        self.console.insert(tk.END, p.stdout)
        self.console.insert(tk.END, p.stderr)

        if p.returncode == 0:
            result = _('ok')
        else:
            result = _('error')

        self.console.insert(tk.END, result+'\n')

        return p.returncode, pdf_filepath


def get_miximg_exe():
    """Return the location of miximg, prefixed by 'python'.

    miximg is searched in the same directory as miximggui.
    """
    gui_dir = os.path.dirname(sys.argv[0])
    miximg = os.path.join(gui_dir, 'miximg')
    return ['python', miximg]


def get_version():
    args = get_miximg_exe() + ['-V']
    p = subprocess.run(args, stdout=subprocess.PIPE)
    return p.stdout


def main():
    root = tk.Tk()
    miximg_version = get_version()
    root.title(miximg_version)
    app = Application(master=root)
    app.mainloop()


if __name__ == '__main__':
    main()
